version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/packages/oidc-jwt-verify"
      - "/packages/oidc-jwt-verify-tachyon"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "*"
        dependency-type: "production"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]